name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx cypress install
      - uses: nrwl/nx-set-shas@v4

      # Run lint for Daskit
      - name: Run Lint for Daskit
        run: npm run lint:Daskit

      # Run tests for Daskit
      - name: Run Tests for Daskit
        run: npx nx test Daskit

      # Run Nx affected command for lint, test, build, and e2e
      - run: npx nx affected -t lint test build e2e
