name: Test

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx cypress install
      - uses: nrwl/nx-set-shas@v4

      # Run tests for Daskit
      - name: Run Tests for Daskit
        run: npx nx test Daskit

      # Run Nx affected command for e2e tests
      - run: npx nx affected -t e2e
